name: dagger
on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - name: Run Dagger pipeline
        run: |
          COMMIT_SHA=$GITHUB_SHA go run main.go
